# ======================================================================
# Site settings
# ======================================================================

name: "visual assault"
description: Internet Creators
url: http://visual-assault.org

# ======================================================================
# Build settings
# ======================================================================
markdown: kramdown
paginate: 10
permalink: pretty


# ======================================================================
# Options
# ======================================================================
color: "#CA4A4C"
