# ======================================================================
# Site settings
# ======================================================================

name: "visual assault"
description: Internet Creators
url: http://visual-assault.org

# ======================================================================
# Build settings
# ======================================================================
markdown: kramdown
paginate: 10
permalink: pretty

# ======================================================================
# Project settings
# ======================================================================
exclude: [
  bower.json,
  Gemfile,
  Gemfile.lock,
  gruntfile.js,
  package.json,
  node_modules,
  LICENSE,
  README.md
]
